CREATE TABLE Utilisateur (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    adresseMail VARCHAR(255) NOT NULL UNIQUE,
    motDePasse VARCHAR(255) NOT NULL
);

CREATE TABLE PlaceHangard (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    placeHangard1 INTEGER NOT NULL,
    placeHangard2 INTEGER NOT NULL
);
